# Generated by Django 3.0.5 on 2020-04-06 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dataset_path',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(regex='gs:\\/\\/(([a-zA-Z0-9_+.-]+)(\\/))+([a-zA-Z0-9_+.-]+)')]),
        ),
    ]
