# Generated by Django 3.0.5 on 2020-06-27 10:17

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200613_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remote_export',
            field=models.CharField(default='None', help_text='Remote export path (GS or S3)', max_length=500, validators=[mainapp.validators.validate_remote_path], verbose_name='Remote Storage'),
        ),
    ]
