# Generated by Django 3.0.5 on 2020-05-10 15:25

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200406_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dataset_format',
            field=models.CharField(choices=[('text', 'Text file'), ('text-dir', 'Directory containing text files'), ('image-dir', 'Directory containing image files'), ('audio-dir', 'Directory containing audio files')], default='text', help_text='Format of your dataset', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='dataset_path',
            field=models.CharField(max_length=500, validators=[mainapp.models.validate_dataset_path]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of your project', max_length=20, unique=True),
        ),
    ]
