# Generated by Django 3.0.5 on 2020-05-15 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_auto_20200510_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='server_pid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='server_port',
        ),
        migrations.AddField(
            model_name='project',
            name='export_format',
            field=models.IntegerField(choices=[(1, 'None/ No export'), (2, 'JSON'), (3, 'CSV'), (4, 'TSV'), (5, 'CONLL')], default=1, help_text='Export format for labelled data'),
        ),
        migrations.AlterField(
            model_name='project',
            name='config',
            field=models.TextField(help_text='Label studio config'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dataset_path',
            field=models.CharField(help_text='Path where dataset is stored', max_length=500, validators=[mainapp.models.validate_dataset_path]),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(help_text='Manager of this project', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initialized'), (2, 'Active'), (3, 'Disabled'), (4, 'Completed')], default=1, help_text='Status of project'),
        ),
    ]
