# Generated by Django 3.0.5 on 2020-05-23 07:02

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200515_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='config',
            field=models.TextField(help_text='Label studio config', validators=[mainapp.models.validate_label_config]),
        ),
    ]
